name: Mac

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Cocoa
    runs-on: macos-latest
    steps:
      - name: Clone Project
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd src
          make -f Makefile.osx
